spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/webkit
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect